spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
    password: GARYbw060132
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Welcome to Spring Boot REST API by Gary Tin (PROD Mode)
